### ISSUE TITLE
Simple (open) PDF to text service

### ISSUE THREAD

**Issue by rgrp** [okfn/ideas#52]
Looking for a simple online service to convert PDF to plain text. Features wanted:

- Preferably open (i.e. underlying code is open)
- Service has API
- OCR *not* required (but a bonus) - working on "normal" PDFs (not scan PDFs)

If it does not exist would consider building.

*Please add suggestions, ideas and comments in the comments*

### Tools and Libraries (only open-source)

Taken from this **[gist list of pdf 2 xxx tools](https://gist.github.com/rgrp/5844485)**

cf also http://okfnlabs.org/dataconverters/ PDF section

#### Generic (PDF -> text)

* [PDFMiner][pdfminer] - PDFMiner is a tool for extracting information from PDF documents. Unlike other PDF-related tools, it focuses entirely on getting and analyzing text data. PDFMiner allows one to obtain the exact location of text in a page, as well as other information such as fonts or lines. It includes a PDF converter that can transform PDF files into other text formats (such as HTML). It has an extensible PDF parser that can be used for other purposes than text analysis.
  * Pure python
* [pdftohtml][] - pdftohtml is a utility which converts PDF files into HTML and XML formats. Based on xpdf
* [pdftoxml][] - command line utility to convert PDF to XML built on poppler.
* [docsplit][] - part of DocumentCloud. Docsplit is a command-line utility and Ruby library for splitting apart documents into their component parts: searchable UTF-8 plain text via OCR if necessary, page images or thumbnails in any format, PDFs, single pages, and document metadata (title, author, number of pages...)
* [pypdf2xml][] - convert PDF to XML. Built on pdfminer. Started as an alternative to poppler's pdftoxml, which didn't properly decode CID Type2 fonts in PDFs.
* [pdf2htmlEX][] - Convert PDF to HTML without losing text or format. C++. Fast.

[pdf2htmlEX]: http://coolwanglu.github.io/pdf2htmlEX/
[pypdf2xml]: https://github.com/zejn/pypdf2xml
[docsplit]: http://documentcloud.github.io/docsplit/
[pdfminer]: http://www.unixuser.org/~euske/python/pdfminer/
[pdftohtml]: http://pdftohtml.sourceforge.net/
[pdftoxml]: http://pdftoxml.sourceforge.net/

#### Tables from PDF

* https://github.com/okfn/pdftables (Was scraperwiki but no longer seems to be available so here is a fork)
* <http://tabula.nerdpower.org/> - open-source, designed specifically for tabular data but looks a bit of a pain to set up
* <http://pdftoxml.sourceforge.net/> - one of the better for tables but have not used for a while
* <http://pdftohtml.sourceforge.net/> - linux only afaict
* [pdf.js](http://mozilla.github.io/pdf.js/) - you probably want a fork like [pdf2json](https://github.com/modesty/pdf2json) or [node-pdfreader](https://github.com/jviereck/node-pdfreader) that integrates this better with node. I have not tried this on tables though ...
* Using scraperwiki + pdftoxml - see this recent tutorial [Get Started With Scraping – Extracting Simple Tables from PDF Documents][scoda-simple-tables]

[scoda-simple-tables]: http://schoolofdata.org/2013/06/18/get-started-with-scraping-extracting-simple-tables-from-pdf-documents/

### Existing open services

* http://pdfx.cs.man.ac.uk/ - has a nice command line interface
  * Is this open? Says at [bottom of usage](http://pdfx.cs.man.ac.uk/usage) that it is powered by http://www.utopiadocs.com/
* Scraperwiki - https://views.scraperwiki.com/run/pdf-to-html-preview-1/ and [this tutorial](http://blog.scraperwiki.com/2010/12/17/scraping-pdfs-now-26-less-unpleasant-with-scraperwiki/)

### Existing proprietary free or paid-for services

* http://www.newocr.com/ - free, no API
* http://www.free-ocr.com/ - free, no API, captcha
* http://www.onlineocr.net/ - free
* http://captricity.com/

Google app engine used to do this http://developers.google.com/appengine/docs/python/conversion/overview

### By Language

@maxogden has this list of Node libraries and tools:

https://gist.github.com/maxogden/5842859

Here's a gist showing how to use pdf2json: https://gist.github.com/rgrp/5944247

## Colophon

Originally: http://ideas.okfn.org/ideas/106/pdf-tiff-scan-to-text-conversion-service/

**Comment by mattfullerton** [comment]
I have a working version of Tika dev (1.8) with tesseract here: http://beta.offenedaten.de:9998/tika

This will give simple text back from a PDF. Nothing fancy.

Test by doing things like:

    curl -T mypdf.pdf http:///beta.offenedaten.de:9998/tika

You can run your own using Docker by doing:

    sudo docker build -t tika github.com/mattfullerton/tika-tesseract-docker
    sudo docker run -d -p 9998:9998 tika

I'm very open to improvements to the Docker build files, I am no expert there.

OCR is supported (for images), but what is lacking now (AFAIK) is detection that standard text extraction from a PDF 'failed' with a fallback to tesseract. We should look into that.

**Comment by rgrp** [comment]
FIXED / DUPLICATE. I think this is now done - really subsumed in #88 and our summary of tools is in http://okfnlabs.org/blog/2016/04/19/pdf-tools-extract-text-and-data-from-pdfs.html
