### ISSUE TITLE
Open Data Case Studies Database

### ISSUE THREAD

**Issue by gr33ndata** [okfn/ideas#83]
*I am not sure if such thing already exists or not*

Whenever I am at the process of creating a presentation, I have to consult google search for some case studies regarding open gov data, how it was done, how it helped making people's life easier, etc.

So, I am thinking of a platform, where we can document open data projects all over the world, and if there are case studies about them. The case studies should be categorized by country, whether it was done by government, local government or by the community as a crowdsourced project. The platform's database should also include the contact persons, tools and softwares used, related research projects and news. How such data was useful and listings of news stories made out of it. May be something a la CruchBase but for Open Data projects and case studies. 

To put you in picture, I am thinking of projects such as WhereDoesMyMoneyGo, TheyWorkForYou, Data.gov.uk, HarassMap, data.WorldBank.org, BroadbandMap.gov,

**Comment by rgrp** [comment]
@gr33ndata I'm going to close this in favour of the Value Stories that are now part of the Open Data Handbook http://opendatahandbook.org/value-stories/en/ - to suggest more for inclusion just open an issue on the open data handbook repo - see http://opendatahandbook.org/contribute/
