### ISSUE TITLE
Opensource OCR Service (PDF / TIFF / Scan to Text Conversion Service)

### ISSUE THREAD

**Issue by rgrp** [okfn/ideas#88]
Originally: http://ideas.okfn.org/ideas/106/pdf-tiff-scan-to-text-conversion-service/

**Note: for generic PDF to text (including but not necessarily OCR) - see #52 (simple pdf to text service)**

Quote from Tim:

> Last weekend, I created an OCR pipeline with OCRopus, Tesseract & Celery/RabbitMQ. I need to do a little bit of work to make it available as a web service.
>
> OCRopus does layout analysis, splitting the image into lines/words. These split files is then sent to Tesseract for OCR and reassembled to create hOCR output. Celery is used for ad-hoc clustering, making it trivial to add more processing capacity.

**Comment by mattfullerton** [comment]
I have a working version of Tika dev (1.8) with tesseract here: http://beta.offenedaten.de:9998/tika

Test by doing things like:

    curl -T multipage_tiff_example.tif http:///beta.offenedaten.de:9998/tika

Fuller instructions here:
https://wiki.apache.org/tika/TikaOCR

You can run your own using Docker by doing:

    sudo docker build -t tika github.com/mattfullerton/tika-tesseract-docker
    sudo docker run -d -p 9998:9998 tika

I'm very open to improvements to the Docker build files, I am no expert there.

What is lacking now (AFAIK) is detection that standard text extraction from a PDF 'failed' with a fallback to tesseract. We should look into that.

**Comment by chrismattmann** [comment]
Hey @mattfullerton good work - we're still working through MultiCompositeParsers in Tika (having multiple for a single type instead of our AutoDetect algorithm which picks the best one). We did a work around in Tika 1.7 and 1.8-dev (so far) to combine the ImageExtractor for metadata and then call Tesseract on images. However, for PDF if you want Tesseract to be called, you can always override the declared Mime types for the parser and/or sub-class it and rebuild Tika to get it to work on PDFs.

**Comment by mattfullerton** [comment]
@chrismattmann Thanks for the tips. Concretely, does that mean that with some passed config there will be support for using tesseract on PDFs instead of the default PDF parser (i.e. client detects if OCR is needed)? Or do you intend to go further and detect the lack of text in the PDF internally (i.e. server detects if OCR is needed)?

**Comment by rgrp** [comment]
@mattfullerton just want to say this really excellent - and do ping the labs list to let them know of your progress (and would you like to do a quick blog post?)

**Comment by pudo** [comment]
Hi all, just wanted to share a quick update on the document processing pipeline I've been working on, which consists of [docpipe](https://github.com/pudo/docpipe) (a document processing tool with configurable pipelines) and [barn](https://github.com/pudo/barn) (an OFS knock-off which a slightly more comprehensive API, also used in the openspending S3 data storage branch).

I've invested quite a lot of time into both recently, making sure barn runs against S3 which should be good in terms of the original centipede idea of having pipeline components run on different hosts but access the same virtual data store. At the same time, I've hacked up docpipe to have full support for textract (which does roughly the same thing as Tika, in Python).

All of this is the backend to an app called [aleph](http://aleph.grano.cc/search) which I'm using to allow journos to search and tag documents. The whole pipeline is a bit slow, but getting there. 

Would be cool to see if there are any docking points?

**Comment by mattfullerton** [comment]
@rgrp I made a post to the list at the time: https://lists.okfn.org/pipermail/okfn-labs/2015-January/001548.html 
I'll work on a blog post

@pudo That's great that things are moving forward with the pipeline approach and that it includes textract. Am I right that what is still missing is the web api? Or maybe I missed it.

**Comment by mattfullerton** [comment]
Blog post: http://okfnlabs.org/blog/2015/02/21/documents-to-text.html

**Comment by rgrp** [comment]
This is fantastic @mattfullerton - will tweet out more monday!

I'd also like to offer a nice url for the service e.g. tika.okfnlabs.org (if we can think of an even cooler subdomain let me know!). This would not require a move of server - just configuring apache/nginx at your end and setting up DNS for the subdomain with open knowledge sysadmins.

wdyt?

**Comment by todrobbins** [comment]
Does Tika offer JP2 support? Just curious about other archival image types.

**Comment by mattfullerton** [comment]
@rgrp Good idea, as long as @ddie has no objections. The alternative of course is to try out the docker image on a labs machine. ATM there is nothing to set up at our end (although nginx would let us drop the port) tika.okfnlabs is fairly clear, but we could also go for something fun like text. or givemetext. or x2text...

@todrobbins  Yes: http://svn.apache.org/repos/asf/tika/trunk/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml (search for jpeg or jp2)

**Comment by rgrp** [comment]
givemetext.okfnlabs.org sounds great. a docker image also sounds really great - but requires other work so let's start with dns.

**Comment by rgrp** [comment]
@mattfullerton shall we ask @nigelbabu do set up the dns for this and you put in the ServerName alias in Apache/Nginx? I'm sure @ddie has no objections re the domain name.

**Comment by nigelbabu** [comment]
This has already been requested and setup.

**Comment by rgrp** [comment]
@nigelbabu awesome! @mattfullerton you need to set the server alias - http://givemetext.okfnlabs.org/ is still offenendaten ;-)

**Comment by mattfullerton** [comment]
There's not a whole lot I can do about that given that there is no web
front end (yet). On the Tika port it works.

**Comment by rgrp** [comment]
@mattfullerton not sure I understand. You just need to do a reverse proxy from givemetext.okfnlabs.org on port 80 to your thing running on whatever port you have. Is the site using nginx or apache as main webserver? if you let us know we can help.

**Comment by mattfullerton** [comment]
I think its nginx - I was just doubting the logic of putting the thing on port 80. Right now these are the two possibilities for showing people when they arrive at givemetext.okfnlabs.org:
http://beta.offenedaten.de:9998/
http://beta.offenedaten.de:9998/tika

I haven't promoted the service anywhere as anything other than a listener on that port for PUT requests. And if someone is using it in that way its probably irrelevant what port is in use. If you think it adds value I can add the proxy, but as I would rather serve up a simple one page app on port 80 that allows the uploading of the file to the service and returns the returned text.

**Comment by rgrp** [comment]
Serving it on port 80 is great if you are happy to do that - makes life easier. I'd also server /tika at base location if that's where the action is.

**Comment by mattfullerton** [comment]
That would be logical, just a pity the text there is so boring at present ;-)

**Comment by mattfullerton** [comment]
OK, Done

**Comment by rgrp** [comment]
@mattfullerton what about the nicer front page?

**Comment by mattfullerton** [comment]
I started building a little Angular App to do the upload and show the result a while ago, and then I got busy :) Will get back to it soon...

**Comment by chrismattmann** [comment]
FYI @tpalsulich built a Tika REST upload page

**Comment by tpalsulich** [comment]
See http://tpalsulich.github.io/TikaExamples/. You can upload a file and see what text Tika pulls out.

**Comment by rgrp** [comment]
@chrismattmann / @tpalsulich that's great - @mattfullerton has already built http://givemetext.okfnlabs.org/ (see above part of the thread). Perhaps we can join forces?

**Comment by mattfullerton** [comment]
I will use this instead. Have to update our tika instance so that it supports POSTing instead of PUTing.

@tpalsulich - Does your instance also include tesseract/ocr, and are you looking for traffic? We could include it as a backup server.

**Comment by mattfullerton** [comment]
Done. The Docker image is now on Tika 1.9, and I added CORS for the service as well so that other web apps can use it.

http://givemetext.okfnlabs.org/ - Web UI, proxied from http://mattfullerton.github.io/TikaExamples/
http://givemetext.okfnlabs.org/tika - proxied from http://givemetext.okfnlabs.org:9998/tika (different from before, where / was proxied to this)

http://givemetext.okfnlabs.org:9998 is open as before but without CORS header

**Comment by rgrp** [comment]
awesome - and we are too to have a standard labs bootstrap theme we can apply to make it look swish ;-)

**Comment by mattfullerton** [comment]
There's a typo in there somewhere. We do have one or we don't?

**Comment by rgrp** [comment]
fixed - we are about to have one (literally a couple of days).

**Comment by tpalsulich** [comment]
@mattfullerton, no, I don't think it has Tesseract installed (just tried parsing the Google logo -- nothin').

No, I'm not looking for a lot of traffic. I intended the site as more of a quick demonstration of what Tika can do. I happy you guys found it useful!

**Comment by chrismattmann** [comment]
@tpalsulich we could probably contact Rackspace and ask them what they think about the traffic, etc. @rgrp @mattfullerton would be happy to join forces! :) FYI too I just completed http://github.com/chrismattmann/tika-python/ which entirely relies now on the REST server and exposes Translation, Language Detection and the full suite of things to make it really usable entirely as a Python library to Tika. So, great timing.

@tpalsulich worst comes to worse, can't they just fork your code and run your code on their OKFN servers?

**Comment by mattfullerton** [comment]
@chrismattmann We already had a Tika instance running (actually generously hosted by OKF Germany), just without an HTML upload button. @tpalsulich frontend does that and I forked it yesterday: http://www.givemetext.okfnlabs.org/.

**Comment by tpalsulich** [comment]
@mattfullerton, awesome! I'm happy you like it. But, I'm getting a DNS lookup error when loading http://www.givemetext.okfnlabs.org/.

**Comment by mattfullerton** [comment]
Oops! No www.

**Comment by tpalsulich** [comment]
That was it. Working now. :+1:

**Comment by chrismattmann** [comment]
woot :+1: great work @mattfullerton @tpalsulich !

**Comment by rgrp** [comment]
@mattfullerton theme is now ready for you try - see http://okfnlabs.org/app-theme/ and https://github.com/okfn/app-theme. This is generic and you can adapt as you want.

**Comment by rgrp** [comment]
@mattfullerton some quick thoughts / suggestions:

- Great to see new theme live on givemetext!
- Where is the source repo for this (is there a mattfullerton/givemetext ?)
- Would it be worth quickly tweaking http://okfnlabs.org/blog/2015/02/21/documents-to-text.html to have the new urls

Website tweaks:

- Would it be worth adding some small API examples to front page somewhere below main form (perhaps also link to blog post ...)
- Could we add a small tagline making clear what this is for the uninitiated e.g. "An easy to use **free** web service to extract text from PDFs and other documents - OCR support included!"
- Can we have support for passing a URL to a file online as well as uploading?

**Comment by mattfullerton** [comment]
@rgrp All good ideas, especially the examples I wanted to do. I'm not really finished with the theme either, that was done very quickly. Just a bit swamped at the moment.

Regarding the source repo, in case its not clear - my only contribution here is creating a Dockerfile that gets the slightly complicated Tika, and specifically Tika-server, up and running with OCR support built in. Tika is an Apache project: https://tika.apache.org/
My small contribution is here: https://github.com/mattfullerton/tika-tesseract-docker

Hence getting support for file URLs within the API (if not already there, I'll have to look) would require modifying Tika itself. I'll look into it but the Tika developers would have the final say; the alternative of course would be our own little micro man-in-the-middle service to download the link in the background.

**Comment by rgrp** [comment]
@mattfullerton got you re time and thanks for flagging the repo - i can open issues there going forward - and people can contribute there (e.g. i assume the front page code is there).

Re the url point: do you have to modify Tika?I thought Tika could take a "stream" like object - and you can just open a url as a stream. Worse case you cache the URL contents to disk as file and then load.

**Comment by jaakkokorhonen** [comment]
@rgrp any plans to make OCR with Froide? We are getting blacked FOI documents into http://tietopyynto.fi, and are looking for a solution to read the scanned or bitmapped documents back into data.

**Comment by chrismattmann** [comment]
@rgrp @mattfullerton Tika can take a stream and yes you can open a URL as a stream to it. See: http://wiki.apache.org/tika/TikaJAXRS#Extracting_A_Document_From_A_URL

**Comment by cleder** [comment]
maybe a bit OT but have a look at https://pypi.python.org/pypi/ocrmypdf

**Comment by mattfullerton** [comment]
@jaakkokorhonen - It may be of little help as its a Ruby project, but the service is being used by kleineanfragen.de: https://github.com/robbi5/kleineanfragen/blob/master/app/jobs/extract_last_modified_from_paper_job.rb#L34

**Comment by mattfullerton** [comment]
@chrismattmann I'm running a very recent version of the latest Tika and can't get the URL processing to work. Would you happen to have a complete curl command for a URL that works? The example in the link is not for a real URL.

**Comment by robbi5** [comment]
@mattfullerton @chrismattmann Tika removed the URL processing feature again, see https://issues.apache.org/jira/browse/TIKA-1690

**Comment by mattfullerton** [comment]
@rgrp I think I've responded to all of your points with an update to http://givemetext.okfnlabs.org/ and a new blog post at http://okfnlabs.org/blog/2015/08/28/give-me-text.html. The URL thing could take a while (see above!).

**Comment by chrismattmann** [comment]
hey @mattfullerton @robbi5 yeah there was a pretty big security hole with that. Sorry posted it before we found the hole.

**Comment by rgrp** [comment]
FIXED. http://okfnlabs.org/blog/2015/08/28/give-me-text.html

@mattfullerton I think we can mark this as closed :-) The service is now operational and i regularly use it. Big well done to you for all your efforts here and creating a great, useful, service.

**Comment by chrismattmann** [comment]
woot! @mattfullerton @rgrp great work

**Comment by mattfullerton** [comment]
Thanks guys. Please post feature requests etc. either on https://issues.apache.org/jira/browse/TIKA/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel if they are specific to the file->text or ocr integration (TIKA) and on https://github.com/mattfullerton/tika-tesseract-docker if specific to the packaging (unlikely) or on https://github.com/mattfullerton/TikaExamples for the web frontend.

**Comment by mattfullerton** [comment]
@nigelbabu - could you update the DNS records as follows:
givemetext.okfnlabs.org			AAAA		2a01:4f8:201:5006::2
www.givemetext.okfnlabs.org		A			148.251.0.14
www.givemetext.okfnlabs.org		AAAA		2a01:4f8:201:5006::2

Thanks!
