### ISSUE TITLE
(Finish) v2.0 Revamp of DataCatalogs.org / DataPortals.org

### ISSUE THREAD

**Issue by rgrp** [okfn/ideas#89]
See remaining issues in v2.0 milestone: https://github.com/okfn/datacatalogs.org/milestones/v2.0%20-%20Major%20Revamp

**Comment by pudo** [comment]
Would be cool to have machine-readable data including a list of API endpoints and what type of catalog software is in use.

**Comment by rgrp** [comment]
@pudo you'll be pleased to know this already went in :-) - see https://github.com/okfn/datacatalogs.org/issues/34

**Comment by pudo** [comment]
Very cool!

**Comment by rgrp** [comment]
FIXED. Pretty much all done: http://dataportals.org/ - plenty more we can do still of course!
